//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("GitTfs")]
[assembly: AssemblyProduct("GitTfs")]
[assembly: AssemblyVersion("0.31.46")]
[assembly: AssemblyFileVersion("0.31.46")]
[assembly: AssemblyInformationalVersion("0.31.46+1031031861e93688279d9a1cadb03dd56d18773d.master")]
[assembly: AssemblyCopyright("Copyright © 2009-2021")]

